# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NodeTest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, status: str=None, project_id: int=None, policy_test_id: int=None, node: str=None, artifact_path: str=None):  # noqa: E501
        """NodeTest - a model defined in Swagger

        :param id: The id of this NodeTest.  # noqa: E501
        :type id: int
        :param status: The status of this NodeTest.  # noqa: E501
        :type status: str
        :param project_id: The project_id of this NodeTest.  # noqa: E501
        :type project_id: int
        :param policy_test_id: The policy_test_id of this NodeTest.  # noqa: E501
        :type policy_test_id: int
        :param node: The node of this NodeTest.  # noqa: E501
        :type node: str
        :param artifact_path: The artifact_path of this NodeTest.  # noqa: E501
        :type artifact_path: str
        """
        self.swagger_types = {
            'id': int,
            'status': str,
            'project_id': int,
            'policy_test_id': int,
            'node': str,
            'artifact_path': str
        }

        self.attribute_map = {
            'id': 'id',
            'status': 'status',
            'project_id': 'projectId',
            'policy_test_id': 'policyTestId',
            'node': 'node',
            'artifact_path': 'artifactPath'
        }
        self._id = id
        self._status = status
        self._project_id = project_id
        self._policy_test_id = policy_test_id
        self._node = node
        self._artifact_path = artifact_path

    @classmethod
    def from_dict(cls, dikt) -> 'NodeTest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NodeTest of this NodeTest.  # noqa: E501
        :rtype: NodeTest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this NodeTest.


        :return: The id of this NodeTest.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this NodeTest.


        :param id: The id of this NodeTest.
        :type id: int
        """

        self._id = id

    @property
    def status(self) -> str:
        """Gets the status of this NodeTest.


        :return: The status of this NodeTest.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this NodeTest.


        :param status: The status of this NodeTest.
        :type status: str
        """

        self._status = status

    @property
    def project_id(self) -> int:
        """Gets the project_id of this NodeTest.


        :return: The project_id of this NodeTest.
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id: int):
        """Sets the project_id of this NodeTest.


        :param project_id: The project_id of this NodeTest.
        :type project_id: int
        """

        self._project_id = project_id

    @property
    def policy_test_id(self) -> int:
        """Gets the policy_test_id of this NodeTest.


        :return: The policy_test_id of this NodeTest.
        :rtype: int
        """
        return self._policy_test_id

    @policy_test_id.setter
    def policy_test_id(self, policy_test_id: int):
        """Sets the policy_test_id of this NodeTest.


        :param policy_test_id: The policy_test_id of this NodeTest.
        :type policy_test_id: int
        """

        self._policy_test_id = policy_test_id

    @property
    def node(self) -> str:
        """Gets the node of this NodeTest.


        :return: The node of this NodeTest.
        :rtype: str
        """
        return self._node

    @node.setter
    def node(self, node: str):
        """Sets the node of this NodeTest.


        :param node: The node of this NodeTest.
        :type node: str
        """

        self._node = node

    @property
    def artifact_path(self) -> str:
        """Gets the artifact_path of this NodeTest.


        :return: The artifact_path of this NodeTest.
        :rtype: str
        """
        return self._artifact_path

    @artifact_path.setter
    def artifact_path(self, artifact_path: str):
        """Sets the artifact_path of this NodeTest.


        :param artifact_path: The artifact_path of this NodeTest.
        :type artifact_path: str
        """

        self._artifact_path = artifact_path
