# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.node_test import NodeTest  # noqa: F401,E501
from swagger_server import util


class PolicyTest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, status: str=None, project_id: int=None, testartifact_id: int=None, policy: str=None, node_tests: List[NodeTest]=None):  # noqa: E501
        """PolicyTest - a model defined in Swagger

        :param id: The id of this PolicyTest.  # noqa: E501
        :type id: int
        :param status: The status of this PolicyTest.  # noqa: E501
        :type status: str
        :param project_id: The project_id of this PolicyTest.  # noqa: E501
        :type project_id: int
        :param testartifact_id: The testartifact_id of this PolicyTest.  # noqa: E501
        :type testartifact_id: int
        :param policy: The policy of this PolicyTest.  # noqa: E501
        :type policy: str
        :param node_tests: The node_tests of this PolicyTest.  # noqa: E501
        :type node_tests: List[NodeTest]
        """
        self.swagger_types = {
            'id': int,
            'status': str,
            'project_id': int,
            'testartifact_id': int,
            'policy': str,
            'node_tests': List[NodeTest]
        }

        self.attribute_map = {
            'id': 'id',
            'status': 'status',
            'project_id': 'projectId',
            'testartifact_id': 'testartifactId',
            'policy': 'policy',
            'node_tests': 'nodeTests'
        }
        self._id = id
        self._status = status
        self._project_id = project_id
        self._testartifact_id = testartifact_id
        self._policy = policy
        self._node_tests = node_tests

    @classmethod
    def from_dict(cls, dikt) -> 'PolicyTest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PolicyTest of this PolicyTest.  # noqa: E501
        :rtype: PolicyTest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this PolicyTest.


        :return: The id of this PolicyTest.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this PolicyTest.


        :param id: The id of this PolicyTest.
        :type id: int
        """

        self._id = id

    @property
    def status(self) -> str:
        """Gets the status of this PolicyTest.


        :return: The status of this PolicyTest.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this PolicyTest.


        :param status: The status of this PolicyTest.
        :type status: str
        """

        self._status = status

    @property
    def project_id(self) -> int:
        """Gets the project_id of this PolicyTest.


        :return: The project_id of this PolicyTest.
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id: int):
        """Sets the project_id of this PolicyTest.


        :param project_id: The project_id of this PolicyTest.
        :type project_id: int
        """

        self._project_id = project_id

    @property
    def testartifact_id(self) -> int:
        """Gets the testartifact_id of this PolicyTest.


        :return: The testartifact_id of this PolicyTest.
        :rtype: int
        """
        return self._testartifact_id

    @testartifact_id.setter
    def testartifact_id(self, testartifact_id: int):
        """Sets the testartifact_id of this PolicyTest.


        :param testartifact_id: The testartifact_id of this PolicyTest.
        :type testartifact_id: int
        """

        self._testartifact_id = testartifact_id

    @property
    def policy(self) -> str:
        """Gets the policy of this PolicyTest.


        :return: The policy of this PolicyTest.
        :rtype: str
        """
        return self._policy

    @policy.setter
    def policy(self, policy: str):
        """Sets the policy of this PolicyTest.


        :param policy: The policy of this PolicyTest.
        :type policy: str
        """

        self._policy = policy

    @property
    def node_tests(self) -> List[NodeTest]:
        """Gets the node_tests of this PolicyTest.


        :return: The node_tests of this PolicyTest.
        :rtype: List[NodeTest]
        """
        return self._node_tests

    @node_tests.setter
    def node_tests(self, node_tests: List[NodeTest]):
        """Sets the node_tests of this PolicyTest.


        :param node_tests: The node_tests of this PolicyTest.
        :type node_tests: List[NodeTest]
        """

        self._node_tests = node_tests
